version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: odoo-db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - odoo-net
    restart: unless-stopped

  odoo:
    image: odoo:17.0
    container_name: odoo-app
    depends_on:
      - db
    env_file: .env
    environment:
      HOST: db
      USER: ${ODOO_DB_USER}
      PASSWORD: ${ODOO_DB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./odoo/custom-addons:/mnt/extra-addons
      - ./odoo/etc/odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo-net
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: odoo-nginx
    depends_on:
      - odoo
    volumes:
      - ./nginx/odoo.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - odoo-net
    restart: unless-stopped


  n8n:
    image: n8nio/n8n:1.79.3
    container_name: n8n-app
    env_file: .env
    environment:
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_HOST=${N8N_HOST}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    ports:
      - "5678:5678"
    volumes:
      - ./n8n:/home/node/.n8n
    networks:
      - odoo-net
    restart: unless-stopped



networks:
  odoo-net:
    driver: bridge